"""empty message

Revision ID: dcd720bf6dfb
Revises: 
Create Date: 2019-11-04 21:06:07.643056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcd720bf6dfb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intents_bot', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'intents_bot', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'intents_bot', type_='foreignkey')
    op.drop_column('intents_bot', 'user_id')
    # ### end Alembic commands ###
